apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ldelossa-dev
  region: us-east-2
  tags:
   usage: "ldelossa-dev"
   owner: "ldelossa"

managedNodeGroups:
- name: ng-1
  instanceTypes:
   - t3.medium
   - t3a.medium
  desiredCapacity: 2
  spot: true
  privateNetworking: true
  volumeType: "gp3"
  volumeSize: 10
  taints:
   - key: "node.cilium.io/agent-not-ready"
     value: "true"
     effect: "NoSchedule"
